### ISSUE TITLE
QTwebkit is deprecated and not available anymore

### ISSUE THREAD

**Issue by cmikovits** [GeoCat/qgis-bridge-plugin#185] opened 2024-08-23 09:30 UTC
**Describe the bug**
With QT 5.6 qtwebkit was removed and this plugin does not work anymore:

https://wiki.qt.io/New_Features_in_Qt_5.6#Removed_Modules

**Comment by GeoSander** [comment] 2024-08-26 13:05
Guess I should use `WebEngine` instead: https://doc.qt.io/qtforpython-6/overviews/qtwebenginewidgets-qtwebkitportingguide.html

**Comment by GeoSander** [comment] 2024-09-05 15:42
This essentially has become a duplicate of #152, which has been re-opened now.
Any progress will be tracked there.

**Closed by GeoSander** 2024-09-05 15:42 UTC
Labels: Qt issue

**Comment by GeoSander** [comment] 2024-10-07 08:18
Fixed and released in [GeoCat Bridge 4.5.0](https://plugins.qgis.org/plugins/geocatbridge/version/4.5.0/).
