### ISSUE TITLE
Existing empty workspaces are overwritten/purged

### ISSUE THREAD

**Issue by kannes** [GeoCat/qgis-bridge-plugin#167] opened 2024-03-28 11:27 UTC
**Describe the bug**
The plugin does not seem to see empty workspaces and overwrites/purges them without asking.

This is problematic because the user might have set up ACL or other settings for them already.

**To Reproduce**
1. Create a new workspace and set it to be isolated
2. Use the plugin to add data to it
3. The workspace (=a new workspace with the same name) is not isolated anymore

**Expected behavior**
The plugin should recognise the existing workspace even if it is empty and not silently overwrite it

**Screenshots**

## Before
I created a workspace called "test" and set it to be isolated.

![image](https://github.com/GeoCat/qgis-bridge-plugin/assets/7661092/63df4a34-3f05-44ca-874b-d8b3384a2229)

## Publishing
I use a QGIS project called "test" with a layer named "world" and click "Publish".

The plugin does not ask about the existing workspace and begins the publishing process.

## Afterwards
A workspace "test" exists, no "isolated" checkmark anymore

![image](https://github.com/GeoCat/qgis-bridge-plugin/assets/7661092/dbb60ca8-c49a-4bc6-9d2b-877e58d79380)

## Publishing again
I restart QGIS, re-open the plugin and I click "Publish" again.

The plugin recognises the existing workspace and asks:
![image](https://github.com/GeoCat/qgis-bridge-plugin/assets/7661092/1a3c869a-81a1-4188-b47e-ea15d126966f)

**Environment info (please complete the following information):**
 - OS: Manjaro
 - QGIS version: 3.22.16
 - Bridge version: 4.4.1
 - Python version: 3.11.0

**Additional context**
https://example.com/geoserver/rest/workspaces.json was queried by the plugin and it contained the "iso" workspace at any time.

https://example.com/geoserver/rest/workspaces/iso/layers.json was queried by the plugin and it did not contain any data at first (this might be why it thinks the workspaces can be recreated from scratch?). It contained data after the layer was published via the plugin (this might be why it recognises the workspace as existing).

**Comment by kannes** [comment] 2024-03-28 11:29
I have not checked what the plugin actually does. Maybe it recreates the workspaces any time one publishes?

In that case maybe an option to set e.g. the isolation flag (or ACL too?) might be a good addition.

**Comment by GeoSander** [comment] 2024-03-28 13:02
Hi @kannes,

Believe it or not, but since the first release of Bridge, this is how it was designed to work: Bridge always overwrites the entire workspace if it already exists.
Being able to add layers to an existing workspace (without losing anything) is probably the number 1 feature that users want. We would like to work on that, but we currently have other priorities. Hopefully later this year.

However, I could make a small change that takes the `isolated` setting from the old/original workspace and applies it to the new one of course. The [GeoServer REST API documentation](https://docs.geoserver.org/stable/en/api/#1.0.0/workspaces.yaml) does not mention that setting though, but when I do a `GET` on a workspace, it does return an `isolated` property in the response, so I assume that I can also add that to a `POST` or `PUT`.

Sander

**Comment by kannes** [comment] 2024-04-02 07:42
Oh, oops, I did not realise that. Makes sense :)

For me it does asks about overwriting *sometimes* though and not *always*. Maybe that is indeed a bug? I was super confused when it silently overwrote my existing workspace and its settings with a new one, without that question dialog.

### Setting workspaces to be isolated
I am using POST for creating new isolated workspaces with `<workspace><name>{workspace}</name><isolated>true</isolated></workspace>` successfully in some internal setup scripts.

**Comment by kannes** [comment] 2024-04-02 08:16
Yay, I will be able to spent some worktime on adding:
- Transfer of isolation level to newly re-created (GeoServer) workspace
- Transfer of ACL to newly re-created (GeoServer) workspace

I'll make two tickets shortly and document my work, hopefully it will lead to a PR (or two).

**Comment by kannes** [comment] 2024-04-04 13:45
I slightly refined the initial post with my newly found knowledge :)

The plugin checks for a remote workspace and only shows a message about an existing workspace if that workspace contains layers which the current project does not have. This makes sense for some cases but is potentially lossy and a bit misleading if a remote workspace *does* exist, just without any *layers*. It might contain security rules or other settings that someone cares about.

Even if #168 and #169 are fixed, there are still other settings (e.g. enabled services) that would be gone.

I would argue that the plugin should always warn if a remote workspace exists.

On the other hand this would be quite annoying, as overwriting the remote workspace is the normal way to "update" it. So the warning would end up being more of a confirmation dialog that plops up all the time for heavy users... Hrrrm, I am not sure.

At least the warning message should be changed so that it does not suggest that "just" the existing identically named layers in the existing workspace will be overwritten. Maybe something like `"A workspace named '{self.workspace}' already exists and contains layers that will be lost. Delete existing workspace to publish this project?"` would be more explicit? Maybe a message at the bottom of the publishing widget could say "A workspace named ... already exists and will be deleted if you publish this project" or something?

I could implement these things but would need your thoughts and decisions :)

**Comment by GeoSander** [comment] 2024-04-05 08:04
Agreed @kannes, the message could be improved. Perhaps change it to `"A workspace named '{self.workspace}' already exists and all its layers will be purged. Do you wish to continue?"

Hopefully later this year, we have time to adjust the UI/UX and also add the "incremental publishing" option, i.e. that users can add layers to an existing workspace without losing all contents.

**Comment by GeoSander** [comment] 2024-05-14 08:13
Closing this, as your PR's have made the workspace overwrite process much less destructive.

**Closed by GeoSander** 2024-05-14 08:13 UTC
Labels: enhancement, GeoServer

**Comment by kannes** [comment] 2024-05-14 08:22
That was my plan as well, thank you! :)
