### ISSUE TITLE
Error when publish layer in QGIS 3.28

### ISSUE THREAD

**Issue by ridhodwid** [GeoCat/qgis-bridge-plugin#161] opened 2024-01-21 09:49 UTC
**Describe the bug**
I try to publish shapefile with style into geoserver 2.22.5 using QGIS 3.28 but error warning appear. I checked on StyleViewer, warning message "Failed to convert to SLD: expected an Element, not Element"

**Screenshots**
![geocat](https://github.com/GeoCat/qgis-bridge-plugin/assets/21953190/9105ca6e-2f9e-45df-8303-51ee9c02abb4)

**Environment info (please complete the following information):**
 - OS: Windows 11
 - QGIS version:3.28 LTR
 - Bridge version: 4.4
 - Python version: 3.9

**Comment by GeoSander** [comment] 2024-01-21 19:41
Hi @ridhodwid ,

Looks like an XML parsing error, which means that [bridgestyle](https://github.com/GeoCat/bridge-style) probably encountered something "weird" (perhaps a new kind of symbology?) that we haven't observed yet.

It would be super helpful if you could attach your QGIS project here. I don't necessarily need the data, just the symbology.

Sander

**Comment by ridhodwid** [comment] 2024-01-22 00:10
Actually, it is only categorized symbol fro polygon
[projectqgz.zip](https://github.com/GeoCat/qgis-bridge-plugin/files/14003282/projectqgz.zip)

**Comment by GeoSander** [comment] 2024-03-21 13:43
Hi @ridhodwid, I think this may have been resolved by the latest `bridgestyle` updates. I wasn't able to reproduce the error, but I did see that the color parsing has changed in recent QGIS releases, causing bad color values in the SLD output.

I submitted release [4.4.1](https://plugins.qgis.org/plugins/geocatbridge/version/4.4.1/) today, so once it has been accepted, you can update Bridge and try it out.
Let me know if you still experiences issues.

**Closed by GeoSander** 2024-03-21 13:43 UTC
Labels: dependency bug, bridgestyle
