### ISSUE TITLE
The styles manager has an error: SLD styles are not displayed after updating to version 4.5.0

### ISSUE THREAD

**Issue by Wo1fgarr** [GeoCat/qgis-bridge-plugin#189] opened 2024-10-07 10:43 UTC
**To Reproduce**
We are updating to version 4.5.0, and the SLD style is no longer displayed in the styles manager.

**Environment info (please complete the following information):**
 - OS: Windows
 - QGIS version: 3.36.1 LTR 
 - Bridge version: 4.5.0

**Screenshots**
In 4.4.2 version
![before](https://github.com/user-attachments/assets/731ff63c-0e2c-4ca1-a1cf-0d9c6c0dc88c)

after update to 4.5.0
![after1](https://github.com/user-attachments/assets/e93e2716-02c0-4336-b962-f72a636fb3ab)
![after2](https://github.com/user-attachments/assets/d89e561c-4c74-4df9-8103-cc00c5212c2e)

**Comment by GeoSander** [comment] 2024-10-07 12:11
Thanks for reporting this @Wo1fgarr, and sorry to hear this.

Did you already restart the QGIS and see if the problem persists?
Seems that Bridge had a hard time picking up the updated `bridgestyle` library.

If you keep on having this problem, could you open the Log Messages panel in QGIS and check if there are any errors on the `GeoCat Bridge` tab and report them here?

I am not on `QGIS 3.36.1` myself (which is not an LTR btw), but I have tested the plugin on Windows 11 with `QGIS 3.34-Prizren` (the actual LTR 😉) and `QGIS 3.38.2-Grenoble`, and I do not get the issue you have.

You should see the following:

<img width="556" alt="image" src="https://github.com/user-attachments/assets/c72785a1-09d6-4f38-b4a9-2eaef1b4ac6c">

Pretty much the same as before, but with improved readability and foldable XML elements.

**Comment by Wo1fgarr** [comment] 2024-10-08 08:06
Good day, @GeoSander !
Thank you for your answer. Yes, I immediately restarted QGIS after updating GeoCat.
The Python console and log do not display any errors:
The errors were seen when I tried to send the style to the server:
![image](https://github.com/user-attachments/assets/b4940829-b25f-4ab8-abc4-44e860ba0452)
I also tried on QGIS 3.34, and when starting a fresh new project, the warnings in Warnings remain.

Uninstalling version 4.5.0 and installing the previous version restores the functionality of the Style Viewer.

Also I recreated a new profile, uploaded GeoCat into it again, created a new connection to the database and as soon as I added data, the message data appeared in the Warnings tab again.
Or do you mean enabling the display of Python errors in the Warnings tab of the Bridge Style Viewer menu? If so, I don't know how to do it, but I'll be happy to enable it and send the result if you teach me how. :smiley:

I can assume that during the update process, some critical module is not being installed.

**Comment by GeoSander** [comment] 2024-10-08 08:18
Hi @Wo1fgarr, thanks for reporting back.
I also checked on another system (MacOS) and there I was actually able to reproduce it.

Indeed it seems that there is an issue with the `bridgestyle` library (a `StopIteration` is raised), causing the style conversion to fail. 

Still cannot reproduce it on my own machine though, but I am going to try to fix it a.s.a.p.!

**Comment by Wo1fgarr** [comment] 2024-10-08 08:48
Thank you so much! I will look forward to a new update :v:

**Comment by GeoSander** [comment] 2024-10-08 10:02
Ok, it should be fixed!
This bug really showed the importance of having good test data btw 😏 

I have pushed the new `4.5.1` release to the QGIS plugin repository just now. 
It might take some time before they approve it, so you probably won't see it yet.

Thanks again for reporting this critical issue! 🥇👏 
Most of the time, no one takes the effort to do so...

**Closed by GeoSander** 2024-10-08 10:02 UTC
Labels: bug, bridgestyle

**Comment by GeoSander** [comment] 2024-10-10 10:35
@Wo1fgarr The plugin just got approved, so you should be able to update now 🙂

**Comment by Wo1fgarr** [comment] 2024-10-10 11:41
@GeoSander Oh, awesome! :fire: Thank you, I installed the update and it worked! Great job:confetti_ball::confetti_ball::confetti_ball:
